apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-visualizationserver
  name: ml-pipeline-visualizationserver
spec:
  selector:
    matchLabels:
      app: ml-pipeline-visualizationserver
  template:
    metadata:
      labels:
        app: ml-pipeline-visualizationserver
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: io.kr.private-ncr.ntruss.com/ncp-kf-install-registry/ml-pipeline/visualization-server:1.0.0
        imagePullPolicy: IfNotPresent
        name: ml-pipeline-visualizationserver
        ports:
        - containerPort: 8888
