apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-deployer-deployment
  labels:
    app: cache-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-deployer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cache-deployer
    spec:
      containers:
      - name: main
        image: io.kr.private-ncr.ntruss.com/ncp-kf-install-registry/ml-pipeline/cache-deployer:1.0.0
        imagePullPolicy: Always
        env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: kubeflow-pipelines-cache-deployer-sa
      restartPolicy: Always
