apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
commonLabels:
  kustomize.component: mxnet-operator
images:
- name: io.kr.private-ncr.ntruss.com/ncp-kf-install-registry/kubeflow/mxnet-operator
  newName: io.kr.private-ncr.ntruss.com/ncp-kf-install-registry/kubeflow/mxnet-operator
  newTag: v1.0.0-20200625
