apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-scheduledworkflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: ml-pipeline-scheduledworkflow
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: io.kr.private-ncr.ntruss.com/ncp-kf-install-registry/ml-pipeline/scheduledworkflow:1.0.0
        imagePullPolicy: IfNotPresent
      serviceAccountName: ml-pipeline-scheduledworkflow
