apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
- name: io.kr.private-ncr.ntruss.com/ncp-kf-install-registry/kubeflow-images-public/pytorch-operator
  newName: io.kr.private-ncr.ntruss.com/ncp-kf-install-registry/kubeflow-images-public/pytorch-operator
  newTag: vmaster-gd596e904
