apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  default:
    predictor:
      minReplicas: 1
      sklearn:
        storageUri: "gs://kfserving-samples/models/sklearn/iris"
